spring:
  redis:
    cluster:
      nodes: 192.168.140.141:8001,192.168.140.139:8002,192.168.140.140:8003,192.168.140.141:8004,192.168.140.139:8005,192.168.140.140:8006
      lettuce:
    host: 192.168.140.141
    # 连接超时时间（记得添加单位，Duration）
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0 # Redis数据库索引（默认为0）
    port: 8001 # Redis服务器连接端口
#    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  cache:
    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
    type: redis
logging:
  level:
    com.xkcoding: debug
